name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: "Ubuntu update"
      run: |
        sudo apt update
        sudo apt install check
    -
      name: "libDAQ, The Data AcQuisition Library"
      run: |
        git clone --recurse-submodules --branch=v3.0.12 --depth=1 https://github.com/snort3/libdaq.git
        cd libdaq && ./bootstrap && ./configure && make && sudo make install
    -
      name: "libdnet, interface to several low-level networking routines"
      run: |
        git clone --recurse-submodules --branch=libdnet-1.16.4 --depth=1 https://github.com/ofalk/libdnet.git
        cd libdnet && ./configure && make && sudo make install
    -
      name: "flex, the fast lexical analyzer generator"
      run: |
        git clone --recurse-submodules --branch=v2.6.4 --depth=1 https://github.com/westes/flex.git
        cd flex && ./autogen.sh && ./configure && make check && sudo make install
    - 
      uses: actions/checkout@v3
    - 
      name: configure
      run: ./configure_cmake.sh
    - 
      name: make
      run: make
    - 
      name: make check
      run: make check
    - 
      name: make distcheck
      run: make distcheck
