name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: "libDAQ"
      run: |
        git clone --recurse-submodules --branch=v3.0.12 --depth=1 https://github.com/snort3/libdaq.git
        cd libdaq
        ./bootstrap
        ./configure
        make
        make install
    - 
      uses: actions/checkout@v3
    - 
      name: configure
      run: ./configure_cmake.sh
    - 
      name: make
      run: make
    - 
      name: make check
      run: make check
    - 
      name: make distcheck
      run: make distcheck
